FROM python:3.12-slim

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        ca-certificates \
        docker-cli \
        docker-compose \
        ffmpeg \
        nodejs \
        npm \
    && npm install --global @gltf-transform/cli \
    && rm -rf /var/lib/apt/lists/*
